//
//  ConnectedMembershipStore.swift
//  MOTIVO
//
//  M9A.4: StoreKit membership foundation with purchase and restore APIs.
//

import Foundation
import StoreKit
import Combine

@MainActor
final class ConnectedMembershipStore: ObservableObject {

    enum MembershipState: Equatable {
        case unknown
        case loading
        case notEntitled
        case entitled
    }

    enum PurchaseOutcome {
        case verified
        case unverified
        case pending
        case userCancelled
        case failed(Error)
    }

    private enum MembershipStoreError: LocalizedError {
        case unsupportedProduct(String)
        case purchaseAlreadyInProgress
        /// **UNUSED SINCE U5f (F10), AND KEPT AS A GRAVESTONE.** A verified
        /// purchase followed by an entitlement that had not yet surfaced used to
        /// be reported as a FAILURE. It is not one: Apple completed the purchase.
        /// Do not reintroduce a caller.
        case entitlementMissingAfterVerifiedPurchase
        case unknownPurchaseResult

        var errorDescription: String? {
            switch self {
            case .unsupportedProduct(let productID):
                return "Unsupported StoreKit product: \(productID)"
            case .purchaseAlreadyInProgress:
                return "A StoreKit purchase is already in progress."
            case .entitlementMissingAfterVerifiedPurchase:
                return "The purchase was verified, but no active Études Connected entitlement was found."
            case .unknownPurchaseResult:
                return "StoreKit returned an unknown purchase result."
            }
        }
    }

    /// Visibility widened at U5e (was `private`) so the attestation service can
    /// filter entitlements against the SAME list rather than keeping a second
    /// copy of the product identifiers. Two copies of this list would drift, and
    /// the server enforces its own hardcoded set anyway — a client that disagreed
    /// would simply be refused, which is a confusing way to discover a typo.
    /// No behaviour change: the values and every existing use are untouched.
    enum ProductID {
        static let monthly = "com.sdsongs.etudes.connected.monthly"
        static let annual = "com.sdsongs.etudes.connected.annual"

        static let all = [
            monthly,
            annual
        ]
    }

    @Published private(set) var membershipState: MembershipState = .unknown
    @Published private(set) var isRefreshingEntitlement = false

    @Published private(set) var products: [Product] = []
    @Published private(set) var isLoadingProducts = false
    @Published private(set) var productLoadError: Error?

    @Published private(set) var isPurchasing = false
    @Published private(set) var purchaseOutcome: PurchaseOutcome?

    @Published private(set) var isRestoringPurchases = false
    @Published private(set) var restoreError: Error?

    var isEntitled: Bool {
        membershipState == .entitled
    }

    var monthlyProduct: Product? {
        products.first { $0.id == ProductID.monthly }
    }

    var annualProduct: Product? {
        products.first { $0.id == ProductID.annual }
    }

    private var hasStarted = false
    private var transactionUpdatesTask: Task<Void, Never>?
    private var entitlementRefreshTask: Task<MembershipState, Never>?

    func start() {
        guard !hasStarted else { return }
        hasStarted = true

        startTransactionObservation()

        Task {
            await loadProducts()
            await refreshEntitlement()
        }
    }

    /// Purchases a Connected subscription, binding it to this Etudes identity.
    ///
    /// **`appAccountToken` MUST BE THE SERVER-ISSUED BINDING TOKEN (B-24).** It is
    /// generated by `gen_random_uuid()` inside `membership_binding` and fetched
    /// through `MembershipBindingService`; **the client never mints one**. Apple
    /// carries it into the transaction and into every future renewal, which is
    /// what lets the server prove the subscription belongs to this identity
    /// rather than merely that somebody's subscription is active.
    ///
    /// Passing `nil` is the LEGACY shape and is retained deliberately: a member
    /// whose token could not be fetched still gets a working purchase, and the
    /// server's legacy-claim path binds it on a later attestation. Refusing the
    /// purchase instead would turn a recoverable binding hiccup into a lost sale.
    func purchase(_ product: Product, appAccountToken: UUID? = nil) async -> PurchaseOutcome {
        guard ProductID.all.contains(product.id) else {
            let error = MembershipStoreError.unsupportedProduct(product.id)
            let outcome = PurchaseOutcome.failed(error)
            purchaseOutcome = outcome
            return outcome
        }

        guard !isPurchasing else {
            let error = MembershipStoreError.purchaseAlreadyInProgress
            let outcome = PurchaseOutcome.failed(error)
            purchaseOutcome = outcome
            return outcome
        }

        isPurchasing = true
        purchaseOutcome = nil

        defer {
            isPurchasing = false
        }

        do {
            let options: Set<Product.PurchaseOption> = appAccountToken
                .map { [.appAccountToken($0)] } ?? []
            let result = try await product.purchase(options: options)

            switch result {
            case .success(let verificationResult):
                switch verificationResult {
                case .verified(let transaction):
                    await transaction.finish()
                    await refreshEntitlement(forceAfterCurrent: true)

                    // F10. **A VERIFIED TRANSACTION IS A COMPLETED PURCHASE**, and
                    // this used to report `.failed` when the entitlement had not
                    // surfaced by the time the refresh returned. Apple took the
                    // money; calling that "Purchase unavailable" is wrong and
                    // invites the member to buy again.
                    //
                    // The distinction that matters is between a purchase that did
                    // not happen -- userCancelled, unverified, pending, a thrown
                    // error, all still reported honestly below -- and a purchase
                    // that happened whose consequences are still settling. The
                    // second is not a failure and must not be dressed as one.
                    let outcome = PurchaseOutcome.verified
                    purchaseOutcome = outcome
                    return outcome

                case .unverified:
                    let outcome = PurchaseOutcome.unverified
                    purchaseOutcome = outcome

                    return outcome
                }

            case .pending:
                let outcome = PurchaseOutcome.pending
                purchaseOutcome = outcome

                return outcome

            case .userCancelled:
                let outcome = PurchaseOutcome.userCancelled
                purchaseOutcome = outcome

                return outcome

            @unknown default:
                let error = MembershipStoreError.unknownPurchaseResult
                let outcome = PurchaseOutcome.failed(error)
                purchaseOutcome = outcome

#if DEBUG
                print("[Membership] Purchase failed: \(error.localizedDescription)")
#endif

                return outcome
            }
        } catch {
            let outcome = PurchaseOutcome.failed(error)
            purchaseOutcome = outcome

#if DEBUG
            print("[Membership] Purchase failed: \(error)")
#endif

            return outcome
        }
    }

    func restorePurchases() async {
        guard !isRestoringPurchases else { return }

        isRestoringPurchases = true
        restoreError = nil

        defer {
            isRestoringPurchases = false
        }

        do {
            try await AppStore.sync()
            await refreshEntitlement(forceAfterCurrent: true)

        } catch {
            restoreError = error

#if DEBUG
            print("[Membership] Restore purchases failed: \(error)")
#endif
        }
    }

    private func startTransactionObservation() {
        guard transactionUpdatesTask == nil else { return }

        transactionUpdatesTask = Task { @MainActor in
            for await verificationResult in Transaction.updates {
                guard !Task.isCancelled else { return }

                guard case .verified(let transaction) = verificationResult else {
#if DEBUG
                    print("[Membership] Ignored unverified transaction update")
#endif
                    continue
                }

                await transaction.finish()
                await refreshEntitlement(forceAfterCurrent: true)
            }
        }
    }

    func refreshEntitlement(forceAfterCurrent: Bool = false) async {
        if let inFlightTask = entitlementRefreshTask {
            let resolvedState = await inFlightTask.value
            membershipState = resolvedState

            guard forceAfterCurrent else { return }

            entitlementRefreshTask = nil
            await refreshEntitlement()
            return
        }

        isRefreshingEntitlement = true
        if membershipState == .unknown {
            membershipState = .loading
        }

        let refreshTask = Task { @MainActor in
            var resolvedState: MembershipState = .notEntitled

            for await verificationResult in Transaction.currentEntitlements {
                guard case .verified(let transaction) = verificationResult else {
#if DEBUG
                    print("[Membership] Ignored unverified current entitlement")
#endif
                    continue
                }

                guard ProductID.all.contains(transaction.productID) else {
                    continue
                }

                resolvedState = .entitled
                break
            }

            return resolvedState
        }

        entitlementRefreshTask = refreshTask
        let resolvedState = await refreshTask.value

        // A forced refresh may have taken ownership of the slot while this one
        // was finishing. It will publish its own, newer result.
        guard entitlementRefreshTask == refreshTask else { return }

        entitlementRefreshTask = nil
        isRefreshingEntitlement = false
        membershipState = resolvedState
    }

    private func loadProducts() async {
        guard !isLoadingProducts else { return }

        isLoadingProducts = true
        productLoadError = nil

        defer {
            isLoadingProducts = false
        }

        do {
            let loadedProducts = try await Product.products(for: ProductID.all)

            products = loadedProducts.sorted { lhs, rhs in
                switch (lhs.id, rhs.id) {
                case (ProductID.monthly, ProductID.annual):
                    return true
                case (ProductID.annual, ProductID.monthly):
                    return false
                default:
                    return lhs.id < rhs.id
                }
            }

        } catch {
            productLoadError = error

#if DEBUG
            print("[Membership] Failed to load StoreKit products: \(error)")
#endif
        }
    }
}
