//
//  MembershipBindingService.swift
//  MOTIVO
//
//  PHASE 3 · U5e — the pre-purchase binding token (B-24).
//
//  ONE JOB: ask the server for this identity's `appAccountToken` and hand it back.
//  It decides nothing about product mode, entitlement, or membership.
//
//  ── THE CLIENT NEVER INVENTS A TOKEN, AND THAT IS THE POINT ────────────────
//
//  The token is generated by `gen_random_uuid()` inside `membership_binding` and
//  returned by `ensure_membership_binding()`, which **takes no argument** and
//  derives its identity from `auth.uid()` on the verified JWT. So there is no
//  parameter to tamper with, and a caller cannot request another identity's
//  token however the request is forged — which is stronger than validating one.
//
//  **THERE IS NO `UUID()` IN THIS FILE.** A client-minted token would be a value
//  the server never issued, and binding a real Apple subscription to one would
//  put a fabricated identifier at the centre of the ownership protocol. If a
//  future edit needs a UUID here, that edit is wrong.
//
//  ── WHAT IT DOES NOT DO ───────────────────────────────────────────────────
//
//  It does not attest, does not read entitlement, does not consult `AppMode`,
//  `canViewFeed`, or whether a membership row exists. **Solo stays account-free**:
//  this is only reachable for an identity that already authenticated, and an
//  unauthenticated caller gets `.notAuthenticated` without a request being made.
//

import Foundation

@MainActor
enum MembershipBindingService {

    enum BindingFailure: Error, Equatable {
        /// No Connected identity on this device. Solo, or signed out.
        case notAuthenticated
        /// Backend URL/key absent — nothing to call.
        case notConfigured
        /// The stored session could not be refreshed.
        case sessionUnavailable
        /// The server answered, but not with a token we can use.
        case malformedResponse
        case transport(String)
    }

    /// Fetches (creating on first use) this identity's binding token.
    ///
    /// Idempotent by construction: `ensure_membership_binding()` upserts and
    /// RETURNS the surviving row, so concurrent callers receive the same token
    /// rather than one of them missing an uncommitted insert.
    ///
    /// **Deliberately NOT gated on Connected mode.** U5's invariant is
    /// `(locally entitled ∧ hasConnectedIdentity)`, and the visible experience may
    /// legitimately be Solo while this runs.
    static func ensureBindingToken(
        auth: AuthManager,
        reason: String
    ) async -> Result<UUID, BindingFailure> {
        guard auth.hasConnectedIdentity else { return .failure(.notAuthenticated) }
        guard BackendConfig.isConfigured else { return .failure(.notConfigured) }

        // F6's helper: mode-independent, and it does not sign anybody out.
        guard await auth.ensureValidBackendSession(reason: "binding:\(reason)") else {
            return .failure(.sessionUnavailable)
        }

        let result = await NetworkManager.shared.request(
            path: "rest/v1/rpc/ensure_membership_binding",
            method: "POST",
            query: nil,
            jsonBody: Data("{}".utf8)
        )

        switch result {
        case .failure(let error):
            return .failure(.transport(String(describing: error)))
        case .success(let data):
            guard let token = decodeBindingToken(data) else {
                return .failure(.malformedResponse)
            }
            return .success(token)
        }
    }

    /// PostgREST returns a scalar-returning function's value as a bare JSON
    /// string — `"aaaaaaaa-...."`, quotes included. Split out as a pure function
    /// so it is unit-testable without a network or a session.
    ///
    /// **Strict on purpose.** Anything that is not a well-formed UUID is refused
    /// rather than coerced: a malformed token would travel into
    /// `Product.PurchaseOption.appAccountToken` and then into Apple's records,
    /// where it is not cheaply correctable.
    static func decodeBindingToken(_ data: Data) -> UUID? {
        if let raw = try? JSONDecoder().decode(String.self, from: data) {
            return UUID(uuidString: raw)
        }
        // Tolerated only because PostgREST's scalar shape has changed before; a
        // bare unquoted body is still parsed strictly as a UUID.
        let text = String(decoding: data, as: UTF8.self)
            .trimmingCharacters(in: CharacterSet(charactersIn: "\"\n\r "))
        return UUID(uuidString: text)
    }
}
